/********************************************************************
* /Users/ImenAlSamarai/Documents/mbr/Event/MWEventDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /Users/ImenAlSamarai/Documents/mbr/Event/MWEventDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMWEventDictionary();
extern void G__cpp_setup_inheritanceMWEventDictionary();
extern void G__cpp_setup_typetableMWEventDictionary();
extern void G__cpp_setup_memvarMWEventDictionary();
extern void G__cpp_setup_globalMWEventDictionary();
extern void G__cpp_setup_memfuncMWEventDictionary();
extern void G__cpp_setup_funcMWEventDictionary();
extern void G__set_cpp_environmentMWEventDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "src/Event.h"
#include "src/EventFile.h"
#include "src/Shower.h"
#include "src/ArrayData.h"
#include "src/StationData.h"
#include "src/SimData.h"
#include "src/AntennaData.h"
#include "src/ChannelData.h"
#include "src/KGBits.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MWEventDictionaryLN_TClass;
extern G__linked_taginfo G__MWEventDictionaryLN_TBuffer;
extern G__linked_taginfo G__MWEventDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__MWEventDictionaryLN_TObject;
extern G__linked_taginfo G__MWEventDictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_string;
extern G__linked_taginfo G__MWEventDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MWEventDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MWEventDictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MWEventDictionaryLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MWEventDictionaryLN_TVector3;
extern G__linked_taginfo G__MWEventDictionaryLN_ChannelData;
extern G__linked_taginfo G__MWEventDictionaryLN_AntennaData;
extern G__linked_taginfo G__MWEventDictionaryLN_listlEChannelDatacOallocatorlEChannelDatagRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_listlEChannelDatacOallocatorlEChannelDatagRsPgRcLcLiterator;
extern G__linked_taginfo G__MWEventDictionaryLN_Shower;
extern G__linked_taginfo G__MWEventDictionaryLN_StationData;
extern G__linked_taginfo G__MWEventDictionaryLN_ArrayData;
extern G__linked_taginfo G__MWEventDictionaryLN_ArrayDatacLcLEArrayType;
extern G__linked_taginfo G__MWEventDictionaryLN_pairlEintcOdoublegR;
extern G__linked_taginfo G__MWEventDictionaryLN_maplEintcOStationDatacOlesslEintgRcOallocatorlEpairlEconstsPintcOStationDatagRsPgRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_maplEintcOStationDatacOlesslEintgRcOallocatorlEpairlEconstsPintcOStationDatagRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__MWEventDictionaryLN_SimData;
extern G__linked_taginfo G__MWEventDictionaryLN_Channel;
extern G__linked_taginfo G__MWEventDictionaryLN_SensitivityTrace;
extern G__linked_taginfo G__MWEventDictionaryLN_pairlEvectorlEdoublecOallocatorlEdoublegRsPgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_Event;
extern G__linked_taginfo G__MWEventDictionaryLN_listlEAntennaDatacOallocatorlEAntennaDatagRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_listlEAntennaDatacOallocatorlEAntennaDatagRsPgRcLcLiterator;
extern G__linked_taginfo G__MWEventDictionaryLN_TTree;
extern G__linked_taginfo G__MWEventDictionaryLN_TFile;
extern G__linked_taginfo G__MWEventDictionaryLN_DetectorSetup;
extern G__linked_taginfo G__MWEventDictionaryLN_EventFile;
extern G__linked_taginfo G__MWEventDictionaryLN_EventFilecLcLMode;
extern G__linked_taginfo G__MWEventDictionaryLN_EventFilecLcLStatus;
extern G__linked_taginfo G__MWEventDictionaryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__MWEventDictionaryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
